name: Build Emscripten
on:
  push:
    tags:
      - "emscripten-*"
env:
  EM_VERSION: 3.1.64
  EM_CACHE_FOLDER: "emsdk-cache"
  SDL_VERSION: 2.30.5
  SDL_IMAGE_VERSION: 2.8.2
  SDL_MIXER_VERSION: 2.8.0
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: ./emscripten/sdl.sh ${{env.SDL_VERSION}}
      - run: ./emscripten/image.rb ${{env.SDL_IMAGE_VERSION}}
      - run: ./emscripten/mixer.rb ${{env.SDL_MIXER_VERSION}}
      - run: ./emscripten/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/emscripten/SDL.tgz
          asset_name: ${{github.ref_name}}-SDL2-${{env.SDL_VERSION}}-SDL2_image-${{env.SDL_IMAGE_VERSION}}-SDL2_mixer-${{env.SDL_MIXER_VERSION}}-sdk-${{env.EM_VERSION}}.tgz
          body: SDL2-${{env.SDL_VERSION}}, SDL2_image-${{env.SDL_IMAGE_VERSION}}, SDL2_mixer-${{env.SDL_MIXER_VERSION}}, emscripten-${{env.EM_VERSION}}
