name: Build Emscripten
on:
  push:
    tags:
      - 'emscripten-*'
env:
  EM_VERSION: 3.1.35
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: mkdir -p em
      - run: ./em_sdl.rb
      - run: ./em_image.rb
      - run: ./em_mixer.rb
      - run: ./em_pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.4.1
        with:
          file: em/SDL.tgz
          asset_name: SDL-${{github.ref_name}}.tgz
          overwrite: true
