name: Build Emscripten
on:
  push:
    tags:
      - 'emscripten-*'
env:
  EM_VERSION: 3.1.59
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: ./emscripten/sdl.sh
      - run: ./emscripten/image.rb
      - run: ./emscripten/mixer.rb
      - run: ./emscripten/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/emscripten/SDL.tgz
          asset_name: SDL-${{github.ref_name}}.tgz
          overwrite: true
