name: Build Linux
on:
  push:
    tags:
      - 'linux-*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev clang cmake libpulse-dev libpipewire-0.3-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./linux/sdl.sh
      - run: ./linux/image.sh
      - run: ./linux/mixer.sh
      - run: ./linux/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/linux/SDL.tgz
          asset_name: SDL-${{github.ref_name}}.tgz
          overwrite: true
