name: Build Linux
on:
  push:
    tags:
      - 'linux-*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev clang cmake libpulse-dev
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir -p linux
      - run: ./linux_sdl.sh
      - run: ./linux_image.sh
      - run: ./linux_mixer.sh
      - run: ./linux_pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.4.1
        with:
          file: linux/SDL.tgz
          asset_name: SDL-${{github.ref_name}}.tgz
          overwrite: true
