name: Build Macos x86_64
on:
  push:
    tags:
      - 'macos-x86_64-*'
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./macos_sdl.sh x86_64
      - run: ./macos_image.sh x86_64
      - run: ./macos_mixer.sh x86_64
      - run: ./macos_pack.sh x86_64
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.4.1
        with:
          file: macos/SDL.tgz
          asset_name: SDL-${{github.ref_name}}.tgz
          overwrite: true
