name: Build Mingw
on:
  push:
    tags:
      - 'mingw-*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./mingw/sdl.sh
      - run: ./mingw/image.sh
      - run: ./mingw/mixer.sh
      - run: ./mingw/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/mingw/SDL.tgz
          asset_name: SDL-${{github.ref_name}}.tgz
          overwrite: true
