name: Release
on:
  push:
    tags:
      - "*"
env:
  SDL_VERSION: 2.30.5
  SDL_IMAGE_VERSION: 2.8.2
  SDL_MIXER_VERSION: 2.8.0
  EM_VERSION: 3.1.64
  EM_CACHE_FOLDER: emsdk-cache
jobs:
  macos:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./macos/sdl.sh ${{env.SDL_VERSION}}
      - run: ./macos/image.sh ${{env.SDL_IMAGE_VERSION}}
      - run: ./macos/mixer.sh ${{env.SDL_MIXER_VERSION}}
      - run: ./macos/pack.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/macos/SDL.tgz
          asset_name: macos-${{github.ref_name}}-SDL2-${{env.SDL_VERSION}}-SDL2_image-${{env.SDL_IMAGE_VERSION}}-SDL2_mixer-${{env.SDL_MIXER_VERSION}}.tgz
  linux:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt update
      - run: >
          sudo apt install libasound2-dev libpulse-dev
          libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./linux/sdl.sh ${{env.SDL_VERSION}}
      - run: ./linux/image.sh ${{env.SDL_IMAGE_VERSION}}
      - run: ./linux/mixer.sh ${{env.SDL_MIXER_VERSION}}
      - run: ./linux/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/linux/SDL.tgz
          asset_name: linux-${{github.ref_name}}-SDL2-${{env.SDL_VERSION}}-SDL2_image-${{env.SDL_IMAGE_VERSION}}-SDL2_mixer-${{env.SDL_MIXER_VERSION}}.tgz
  mingw:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./mingw/sdl.sh ${{env.SDL_VERSION}}
      - run: ./mingw/image.sh ${{env.SDL_IMAGE_VERSION}}
      - run: ./mingw/mixer.sh ${{env.SDL_MIXER_VERSION}}
      - run: ./mingw/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/mingw/SDL.tgz
          asset_name: mingw-${{github.ref_name}}-SDL2-${{env.SDL_VERSION}}-SDL2_image-${{env.SDL_IMAGE_VERSION}}-SDL2_mixer-${{env.SDL_MIXER_VERSION}}.tgz
  emscripten:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: ./emscripten/sdl.sh ${{env.SDL_VERSION}}
      - run: ./emscripten/image.rb ${{env.SDL_IMAGE_VERSION}}
      - run: ./emscripten/mixer.rb ${{env.SDL_MIXER_VERSION}}
      - run: ./emscripten/pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/emscripten/SDL.tgz
          asset_name: emscripten-${{env.EM_VERSION}}-${{github.ref_name}}-${{github.ref_name}}-SDL2-${{env.SDL_VERSION}}-SDL2_image-${{env.SDL_IMAGE_VERSION}}-SDL2_mixer-${{env.SDL_MIXER_VERSION}}.tgz
